title: Have a Great Day
author: Smiles Davis
email: smilesdavis1@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Subscribe to Have a Great Day! Start each day with a pleasant message at the top of your inbox!

# social links
twitter_username: greatdayemail
github_username:  smilesdavis

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
